### PR TITLE
Redesigned introduction and fixed quirks related to it

### PR DESCRIPTION
**Pull request by FacuA0**
Main changes:

- Remade SVG letter paths to make it simpler and stroke-based instead of fill-based.
- Fixed bug where the animation was shown after it started running.
- Fixed bug (caused by the earlier fix) where the desktop could be briefly visible in the first second before the animation started running.

### CODE REVIEW

**Comment by FacuA0** [comment]
For some reason my earlier commits appeared here, even if they were already merged (maybe it's because of the "Squash and merge" option).

**Comment by CodeHeister** [comment]
Great idea to prevent undefined behavior, but you should also add in your window load listener `if (intro)` to check if it wasn't removed from demo for cooldown, otherwise it will call null Object.

**Comment by FacuA0** [comment]
Ok, editing it.

Edit: Oh, you already made it. Thanks.

**Review by CodeHeister — APPROVED** [review]
Great work

**Pull request merged**
